### ISSUE TITLE
Authentication signature error

### ISSUE THREAD

**Issue by LucasLau00** [tkattkat/popmart-monitor#5]
{"code":"4001","data":null,"message":"Authentication signature error","now":,"ret":4001}

do you happen to know what can i do to prevent this error? 
Have tried submitting with Bearer

**Comment by tkattkat** [comment]
No idea brather. Made this script for a friend when I was drunk. Does it need to be updated?

**Comment by LucasLau00** [comment]
Yup tried debugging and got this error

**Comment by Zyziek055** [comment]
Did you resolve this problem somehow?

**Comment by tkattkat** [comment]
Idk brather my guess is just copy cookies from a browser session and change them in script

**Comment by Zyziek055** [comment]
@LucasLau00 could you please contact me with the solution to that problem if you have one?

**Comment by Zyziek055** [comment]
@tkattkat there's no cookies for this request needed. Is there any chance you could help me with that?

**Comment by gilrodar** [comment]
> @tkattkat there's no cookies for this request needed. Is there any chance you could help me with that? I can pay.

I have a solution for monitoring products. We can chat via Telegram @gilrodar
